import { AbstractContract } from "./contract";
export declare const ConditionalTransfer: AbstractContract;
export declare const NonceRegistry: AbstractContract;
export declare const Registry: AbstractContract;
export declare const StaticCall: AbstractContract;
export declare const Signatures: AbstractContract;
export declare const Transfer: AbstractContract;
export declare const StateChannel: AbstractContract;
export declare const MinimumViableMultisig: AbstractContract;
declare const _default: {
    ConditionalTransfer: AbstractContract;
    NonceRegistry: AbstractContract;
    Registry: AbstractContract;
    StaticCall: AbstractContract;
    MinimumViableMultisig: AbstractContract;
    Signatures: AbstractContract;
    Transfer: AbstractContract;
    StateChannel: AbstractContract;
};
export default _default;
