graph LR
    ms-->ttt
    ms-->fb
    subgraph off-chain state
    fb["<b>Free Balance</b> (ETH) <br> Local Nonce: <tt>k + 1</tt> <br> Alice has 9 ETH <br> Bob has 9 ETH"]
    ttt["<b>TicTacToe App</b> <br> Local Nonce: 0 <br> Winner gets 2 ETH <br><center><b><tt>| &nbsp; | &nbsp; | &nbsp; |<br>| &nbsp; | &nbsp; | &nbsp; |<br>| &nbsp; | &nbsp; | &nbsp; |</tt></b></center>"]
    end
    subgraph on-chain state
    ms["<b>AB Multisignature Wallet</b> <br> Balance: 20 ETH"]
    end