graph LR
    subgraph ConditionalTransaction
        executeAppConditionalTransaction
        executeAppConditionalTransaction.->REGISTRY
        executeAppConditionalTransaction.->NONCE_REGISTRY
        executeAppConditionalTransaction.->depNonceKey
        executeAppConditionalTransaction.->appCfAddress
        executeAppConditionalTransaction.->terms
    end
    subgraph Registry
        proxyCall
    end
    subgraph AppInstance
        setState
        proxyCall-->setState
        setState-->appStateHash
        setState-->nonce
        setState-->timeout
        setState-->0x0
    end
    subgraph MultiSend
        multiSend
        multiSend-->proxyCall
        multiSend-->executeAppConditionalTransaction
    end
    subgraph Multisig
        execTransaction-->multiSend
    end