graph LR
    subgraph ConditionalTransaction
        executeAppConditionalTransaction
        executeAppConditionalTransaction.->REGISTRY
        executeAppConditionalTransaction.->NONCE_REGISTRY
        executeAppConditionalTransaction.->uninstallKey
        executeAppConditionalTransaction.->appCfAddress
        executeAppConditionalTransaction.->terms
    end
    subgraph Registry
        proxyCall
    end
    subgraph AppRegistry
        setState
        proxyCall-->setState
        setState-->appIdentity:AppIdentity
        setState-->req:SignedStateHashUpdate
    end
    subgraph MultiSend
        multiSend
        multiSend-->proxyCall
        multiSend-->executeAppConditionalTransaction
    end
    subgraph Multisig
        execTransaction-->multiSend
    end