graph LR
    subgraph Registry
        proxyCall
    end
    subgraph AppRegistry
        setState
        proxyCall-->setState
        setState-->appIdentity:AppIdentity
        setState-->req:SignedStateHashUpdate
    end