graph LR
  ms-->fb
  subgraph off-chain state
    fb["<b>Free Balance</b> (ETH) <pre></pre> Local Nonce: 0 <pre></pre> Alice has 0 ETH <pre></pre> Bob has 0 ETH"]
  end
  subgraph on-chain state
    ms["<b>AB Multisignature Wallet</b> <pre></pre> Balance: 0 ETH"]
  end