graph LR
    subgraph ConditionalTransaction
        executeAppConditionalTransaction
        executeAppConditionalTransaction.->REGISTRY
        executeAppConditionalTransaction.->NONCE_REGISTRY
        executeAppConditionalTransaction.->uninstallKey
        executeAppConditionalTransaction.->freeBalanceCfAddress
        executeAppConditionalTransaction.->terms
    end
    subgraph MultiSend
        multiSend-->executeAppConditionalTransaction
    end
    subgraph Multisig
        execTransaction-->multiSend
    end