graph LR
    subgraph NonceRegistry
        setNonce
        setNonce.->0
        setNonce.->salt
        setNonce.->1
    end
    subgraph Registry
        proxyCall
    end
    subgraph AppRegistry (Free Balance)
        setState
        proxyCall-->setState
        setState-->appIdentity:AppIdentity
        setState-->req:SignedStateHashUpdate
    end
    subgraph MultiSend
        multiSend
        multiSend-->proxyCall
        multiSend-->setNonce
    end
    subgraph Multisig
        execTransaction-->multiSend
    end